### ISSUE TITLE
I've made a change to the flutter core that will make your emulator look a lot better

### ISSUE THREAD

**Issue by namanix** [DanTup/Flip-8#1]
Hey!

My pull request has just been accepted so soon every image has a quality filter on it. 
Meaning for your project that the chip-8 screen can be set to no quality filter. That will give you sharp edges and no aliassing on the screen.

Here the link of the pull request: https://github.com/flutter/flutter/pull/23329
And the really small update to your code that will make it look really clean!

`currentFrame = new Image.memory(
          frameData,
          gaplessPlayback: true,
          fit: BoxFit.contain,
          filterQuality: FilterQuality.none,
        );`

**Comment by DanTup** [comment]
Sorry for the delay, I left this in my inbox to test after the next release and then stuff got piled on top of it! Just tried this out and it looks excellent, thanks very much! 👍
